<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-SagaStateMachineWorkerService-4be10306-e170-40ec-83da-26f1ce3c457e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.AspNetCore" Version="7.3.1" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.5.5" />
    <PackageReference Include="MassTransit.Extensions.DependencyInjection" Version="7.3.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared.Bus\Shared.Bus.csproj" />
  </ItemGroup>
</Project>
